package com.mycompany.rpg.frontend;

import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author giovanic
 */
public class AcercaDeDialog extends javax.swing.JDialog {

    /**
     * Creates new form AcercaDeDialog
     *
     * @param parent frame propietario
     * @param modal modal
     */
    public AcercaDeDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        btnManualUsuarioAction();
        btnManualTecnicoAction();
    }

    /**
     * Metodo para accionar el boton M. Usuario
     */
    private void btnManualUsuarioAction() {
        btnManualUsuario.addActionListener((ActionEvent evento) -> {
            File tmp = new File("ManualUsuario.pdf");
            if (tmp.exists()) {
                abrirArchivo(tmp);
            } else {
                errorMensaje();
            }
        });
    }

    private void btnManualTecnicoAction() {
        btnManualTecnico.addActionListener((ActionEvent evento) -> {
            File tmp = new File("target/site/apidocs/index.html");
            if (tmp.exists()) {
                abrirArchivo(tmp);
            } else {
                errorMensaje();
            }
        });
    }

    private void abrirArchivo(File file) {
        try {
            File objetoFile = file;
            Desktop.getDesktop().open(objetoFile);
        } catch (IOException ex) {
            Logger.getLogger(AcercaDeDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void errorMensaje() {
        JOptionPane msg = new JOptionPane("No se puede abrir el archivo, probablemente fue borrado",
                JOptionPane.ERROR_MESSAGE);
        JDialog dlg = msg.createDialog("Advertencia");
        dlg.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    Thread.sleep(1300);
                } catch (InterruptedException e) {
                }
                dlg.setVisible(false);
            }
        }).start();
        dlg.setVisible(true);
        dlg.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoTxtArea = new javax.swing.JTextArea();
        btnManualUsuario = new javax.swing.JButton();
        btnManualTecnico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acerda de");
        setResizable(false);

        logoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Proyecto No. 2");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("IPC1B");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Juan Giovani Casia Perez");

        infoTxtArea.setColumns(20);
        infoTxtArea.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        infoTxtArea.setRows(5);
        infoTxtArea.setText("Resumen del Flujo del Juego\nSe inicia una nueva partida, se le asigna 500 de oro al \njugador, se abre la tienda para que pueda comprar \ndos personajes y los objetos que le alcancen. Luego se \nle presenta la Selección de mapas y se inicia el juego.\n\nEl jugador elige un personaje principal y uno \nsecundario en la Selección de personajes, coloca al \nprincipal en una de las casillas del tablero para luego \ncolocar de manera aleatoria a los enemigos en \nalguna de las casillas de planicie disponibles. Por cada \nturno el jugador podrá atacar o moverse, teniendo en \ncuenta que se deberá de tener la opción de utilizar un \nobjeto o de cambiar al otro personaje (en caso de que \nel otro personaje haya caído en batalla y no se cuente \ncon la Semilla de la vida, se deberá de omitir dicha \nopción).\n\nEn cada turno se deberá de mostrar la información del \nturno anterior (los enemigos que se movieron o \natacaron, si el jugador golpeó a un enemigo, etc), así \ncomo la información actual (turno, personaje que \ncontrola, daño y vida del mismo).\n\nEl jugador gana la partida al eliminar a todos los \nenemigos y recibe 250 de oro.\n");
        jScrollPane1.setViewportView(infoTxtArea);

        btnManualUsuario.setText("Manual de Usuario");
        btnManualUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnManualTecnico.setText("Manual Tecnico");
        btnManualTecnico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnManualUsuario)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel2))))
                                        .addGap(42, 42, 42))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(logoLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManualTecnico)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logoLbl)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnManualUsuario)
                        .addGap(14, 14, 14)
                        .addComponent(btnManualTecnico))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManualTecnico;
    private javax.swing.JButton btnManualUsuario;
    private javax.swing.JTextArea infoTxtArea;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logoLbl;
    // End of variables declaration//GEN-END:variables
}
