package com.mycompany.rpg.frontend;

import com.mycompany.rpg.backend.JugadorUs;
import com.mycompany.rpg.backend.ManejadorJugadores;
import com.mycompany.rpg.backend.tablero.CreadorTablero;
import com.mycompany.rpg.backend.util.*;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author giovanic Frame que invoca otras ventana y guarda la informacion
 * generada de estas
 */
public class MenuPrincipalFrame extends javax.swing.JFrame {

    private final ControladorArchivos controlador;
    private TiendaDialog tienda;
    private JuegoFrame frameJuego;
    private InventarioFrame inventarioFrame;
    private ScoreDialog ranking;
    private ManejadorJugadores manejadorJugadores;
    private GenTablero genTablero;
    private Listado<CreadorTablero> tabs;

    /**
     * Creates new form MenuPrincipalFrame
     */
    public MenuPrincipalFrame() {
        initComponents();
        setTitle("Unknow World RPG");
        setLocationRelativeTo(null);

        controlador = new ControladorArchivos();
        manejadorJugadores = new ManejadorJugadores();
        tabs = new Listado<>();

        leerBinario();
        fondo();
    }

    /**
     * Metodo para cambiar el fondo del menu
     */
    private void fondo() {
        JPanelFondo fondo = new JPanelFondo(
                panelMenu,
                "/imagenes/fondo.png");
        panelMenu.add(fondo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnIniciarPartida = new javax.swing.JButton();
        btnTienda = new javax.swing.JButton();
        btnGenTablero = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnRanking = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAyuda = new javax.swing.JMenu();
        JItemAcercaDe = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(555, 828));
        setPreferredSize(new java.awt.Dimension(555, 780));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelMenu.setMaximumSize(new java.awt.Dimension(555, 780));
        panelMenu.setMinimumSize(new java.awt.Dimension(555, 780));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UNKNOW");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WORLD");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RPG");

        btnIniciarPartida.setBackground(new java.awt.Color(0, 0, 0));
        btnIniciarPartida.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        btnIniciarPartida.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarPartida.setText("Iniciar Parida");
        btnIniciarPartida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciarPartida.setOpaque(true);
        btnIniciarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarPartidaActionPerformed(evt);
            }
        });

        btnTienda.setBackground(new java.awt.Color(0, 0, 0));
        btnTienda.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        btnTienda.setForeground(new java.awt.Color(255, 255, 255));
        btnTienda.setText("Tienda");
        btnTienda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTienda.setOpaque(true);
        btnTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiendaActionPerformed(evt);
            }
        });

        btnGenTablero.setBackground(new java.awt.Color(0, 0, 0));
        btnGenTablero.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        btnGenTablero.setForeground(new java.awt.Color(255, 255, 255));
        btnGenTablero.setText("Generacion de Tablero");
        btnGenTablero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenTablero.setOpaque(true);
        btnGenTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenTableroActionPerformed(evt);
            }
        });

        btnInventario.setBackground(new java.awt.Color(0, 0, 0));
        btnInventario.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        btnInventario.setForeground(new java.awt.Color(255, 255, 255));
        btnInventario.setText("Inventario");
        btnInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInventario.setOpaque(true);
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(0, 0, 0));
        btnSalir.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setOpaque(true);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnRanking.setBackground(new java.awt.Color(0, 0, 0));
        btnRanking.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        btnRanking.setForeground(new java.awt.Color(255, 255, 255));
        btnRanking.setText("Ranking");
        btnRanking.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRanking.setOpaque(true);
        btnRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(449, 449, 449)
                .addComponent(jLabel1))
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(455, 455, 455)
                .addComponent(jLabel2))
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(469, 469, 469)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnIniciarPartida))
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnTienda))
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnGenTablero))
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnInventario))
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnSalir))
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnRanking))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addGap(351, 351, 351)
                .addComponent(btnIniciarPartida)
                .addGap(18, 18, 18)
                .addComponent(btnTienda)
                .addGap(18, 18, 18)
                .addComponent(btnGenTablero)
                .addGap(18, 18, 18)
                .addComponent(btnInventario)
                .addGap(18, 18, 18)
                .addComponent(btnRanking)
                .addGap(18, 18, 18)
                .addComponent(btnSalir))
        );

        jMenuAyuda.setText("Ayuda");

        JItemAcercaDe.setText("Acerca de");
        JItemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JItemAcercaDeActionPerformed(evt);
            }
        });
        jMenuAyuda.add(JItemAcercaDe);

        jMenuItem1.setText("Borrar datos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuItem1);

        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JItemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JItemAcercaDeActionPerformed
        AcercaDeDialog ac = new AcercaDeDialog(this, true);
        ac.setLocationRelativeTo(null);
        ac.setVisible(true);
    }//GEN-LAST:event_JItemAcercaDeActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int ax = JOptionPane.showConfirmDialog(
                null,
                "Esta Seguro Que Desea Salir?"
        );

        if (ax == JOptionPane.YES_NO_OPTION) {
            JOptionPane.showMessageDialog(
                    null,
                    "Hasta Pronto..."
            );
            controlador.guardarTableros(tabs);
            controlador.guardarSesionJugadores(manejadorJugadores);
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIniciarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarPartidaActionPerformed
        frameJuego = new JuegoFrame(this, manejadorJugadores, tabs, controlador);
        frameJuego.setVisible(true);
    }//GEN-LAST:event_btnIniciarPartidaActionPerformed

    private void cargarComponenteDialogSeleccion(int op) {
        JDialog selJugadores = new JDialog(this, true);
        selJugadores.setSize(200, 190);
        selJugadores.setLayout(null);
        selJugadores.setResizable(false);
        selJugadores.setTitle("Seleccionar");
        selJugadores.setLocationRelativeTo(null);

        JPanel panelito = new JPanel(null);
        panelito.setBounds(0, 0, selJugadores.getWidth(), selJugadores.getHeight());
        panelito.setBackground(Color.black);
        panelito.setVisible(true);
        selJugadores.add(panelito);

        comboBoxJugadores = new JComboBox<>();
        comboBoxJugadores.setBounds(40, 40, 120, 40);
        for (int i = 0; i < manejadorJugadores.obtenerTamanio(); i++) {
            comboBoxJugadores.addItem(manejadorJugadores.obtenerJugador(i).getNombre());
        }

        JButton btnAceptar0 = new JButton("Aceptar");
        btnAceptar0.setBackground(Color.white);
        btnAceptar0.setForeground(Color.black);
        btnAceptar0.setBounds(60, 100, 80, 40);

        JButton btnAceptar1 = new JButton("Aceptar");
        btnAceptar1.setBackground(Color.white);
        btnAceptar1.setForeground(Color.black);
        btnAceptar1.setBounds(60, 100, 80, 40);

        panelito.add(comboBoxJugadores);
        panelito.add(btnAceptar0);
        panelito.add(btnAceptar1);

        switch (op) {
            case 0 -> {
                btnAceptar1.setVisible(false);
            }
            case 1 -> {
                btnAceptar0.setVisible(false);
            }
        }

        btnAceptar0.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int select = comboBoxJugadores.getSelectedIndex();
                if (select != -1) {
                    selJugadores.setVisible(false);
                    iniciarTienda(manejadorJugadores.obtenerJugador(select));

                } else {
                    selJugadores.setVisible(false);
                    JOptionPane.showMessageDialog(null,
                            "No hay jugadores, inicie una partida antes",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        });

        btnAceptar1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int select = comboBoxJugadores.getSelectedIndex();
                if (select != -1) {
                    selJugadores.setVisible(false);
                    iniciarInventario(manejadorJugadores.obtenerJugador(select));
                } else {
                    selJugadores.setVisible(false);
                    JOptionPane.showMessageDialog(null,
                            "No hay jugadores, inicie una partida antes",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        });

        selJugadores.setVisible(true);
    }

    private void iniciarTienda(JugadorUs jg) {
        this.tienda = new TiendaDialog(this, true, jg);
        this.tienda.setTitle("Tienda: " + jg.getNombre());
        tienda.setLocationRelativeTo(null);
        tienda.setVisible(true);
    }

    private void iniciarInventario(JugadorUs jg) {
        this.inventarioFrame = new InventarioFrame(this, jg);
        inventarioFrame.setTitle("Inventario: " + jg.getNombre());
        inventarioFrame.setLocationRelativeTo(null);
        this.inventarioFrame.setVisible(true);
    }

    private void btnTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiendaActionPerformed
        cargarComponenteDialogSeleccion(0);
    }//GEN-LAST:event_btnTiendaActionPerformed

    private void btnGenTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenTableroActionPerformed
        genTablero = new GenTablero(this, tabs, controlador);
        genTablero.setTitle("Generacion de Tableros");
        genTablero.setLocationRelativeTo(null);
        genTablero.setVisible(true);
    }//GEN-LAST:event_btnGenTableroActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        cargarComponenteDialogSeleccion(1);
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankingActionPerformed
        ranking = new ScoreDialog(this, manejadorJugadores);
        ranking.setVisible(true);
    }//GEN-LAST:event_btnRankingActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controlador.guardarTableros(tabs);
        controlador.guardarSesionJugadores(manejadorJugadores);
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        controlador.eliminarArchivo("persistencia/login/ManejadorJugadores.bin");
        controlador.eliminarPorExtension("persistencia/partidas/", "bin");
        manejadorJugadores = new ManejadorJugadores();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void leerBinario() {
        File f = new File("persistencia/tableros/ListaDeTableros.bin");
        if (f.exists()) {
            FileInputStream file = null;
            try {
                file = new FileInputStream("persistencia/tableros/ListaDeTableros.bin");
                tabs = controlador.leerLogTablero(file);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MenuPrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    file.close();
                } catch (IOException ex) {
                    Logger.getLogger(MenuPrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

        File f1 = new File("persistencia/login/ManejadorJugadores.bin");
        if (f1.exists()) {
            FileInputStream file = null;
            try {
                file = new FileInputStream("persistencia/login/ManejadorJugadores.bin");
                manejadorJugadores = controlador.leerSesionJugadores(file);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MenuPrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    file.close();
                } catch (IOException ex) {
                    Logger.getLogger(MenuPrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    public Listado<CreadorTablero> getTabs() {
        return tabs;
    }

    private javax.swing.JComboBox<String> comboBoxJugadores;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JItemAcercaDe;
    private javax.swing.JButton btnGenTablero;
    private javax.swing.JButton btnIniciarPartida;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnRanking;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTienda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables

    class JPanelFondo extends JLabel {

        private int x = 0;
        private int y = 0;
        private final String path;

        public JPanelFondo(JPanel panel, String path) {
            this.path = path;
            this.x = panel.getWidth();
            this.y = panel.getHeight();
            this.setSize(x, y);
        }

        @Override
        public void paint(Graphics g) {
            ImageIcon img = new ImageIcon(getClass().getResource(path));
            g.drawImage(img.getImage(), 0, 0, x, y, null);
            super.paint(g);
        }
    }
}
