package com.mycompany.rpg.frontend;

import com.mycompany.rpg.backend.JugadorUs;
import com.mycompany.rpg.backend.tienda.Tienda;
import java.awt.Color;
import java.awt.Frame;
import javax.swing.JOptionPane;

/**
 *
 * @author giovanic
 */
public class TiendaDialog extends javax.swing.JDialog {

    private Tienda tienda;
    private JugadorUs jg;

    /**
     * Creates new form TiendaDialog
     *
     * @param parent frame que lo invoca
     * @param modal modalidad especificada
     * @param jg recibe un Jugador
     */
    public TiendaDialog(Frame parent, boolean modal, JugadorUs jg) {
        super(parent, modal);
        this.jg = jg;
        initComponents();

        Color violeta = new Color(128, 0, 255);

        ColorPanel pVista = new ColorPanel(Color.cyan, violeta);
        pVista.setSize(this.getSize());
        panelPersonaje.add(pVista);
        ColorPanel p2Vista = new ColorPanel(Color.cyan, violeta);
        p2Vista.setSize(this.getSize());
        panelItem.add(p2Vista);
        ColorPanel p3Vista = new ColorPanel(Color.cyan, violeta);
        p3Vista.setSize(this.getSize());
        panelMejora.add(p3Vista);

        refrecshLabelOro();
        tienda = new Tienda(jg);
    }

    private void refrecshLabelOro() {
        cantidadOroLbl.setText(jg.getOro() + "");
        cantidadOroLbl.setForeground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoPersj = new javax.swing.ButtonGroup();
        grupoItem = new javax.swing.ButtonGroup();
        grupoMejora = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelPersonaje = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rBtnCaballero = new javax.swing.JRadioButton();
        rBtnArquero = new javax.swing.JRadioButton();
        rBtnMago = new javax.swing.JRadioButton();
        rBtnGigante = new javax.swing.JRadioButton();
        rBtnDragon = new javax.swing.JRadioButton();
        btnComprarPrj = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        panelItem = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rBtnSemilla = new javax.swing.JRadioButton();
        rBtnElixir = new javax.swing.JRadioButton();
        rBtnCapa = new javax.swing.JRadioButton();
        btnComprarItem = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelMejora = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rBtnMasVida = new javax.swing.JRadioButton();
        rBtnMasDanio = new javax.swing.JRadioButton();
        rBtnMasMov = new javax.swing.JRadioButton();
        btnComprarMejora = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cantidadOroLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setLabelFor(panelPersonaje);
        jLabel1.setText("Seleccione un personaje");

        grupoPersj.add(rBtnCaballero);
        rBtnCaballero.setText("Caballero");

        grupoPersj.add(rBtnArquero);
        rBtnArquero.setText("Arquero");

        grupoPersj.add(rBtnMago);
        rBtnMago.setText("Mago");

        grupoPersj.add(rBtnGigante);
        rBtnGigante.setText("Gigante");

        grupoPersj.add(rBtnDragon);
        rBtnDragon.setText("Dragon");

        btnComprarPrj.setText("Comprar Personaje");
        btnComprarPrj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarPrjActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("200 Oro, por personaje");

        javax.swing.GroupLayout panelPersonajeLayout = new javax.swing.GroupLayout(panelPersonaje);
        panelPersonaje.setLayout(panelPersonajeLayout);
        panelPersonajeLayout.setHorizontalGroup(
            panelPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPersonajeLayout.createSequentialGroup()
                        .addComponent(rBtnDragon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnComprarPrj))
                    .addGroup(panelPersonajeLayout.createSequentialGroup()
                        .addComponent(rBtnCaballero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(panelPersonajeLayout.createSequentialGroup()
                        .addGroup(panelPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rBtnMago)
                            .addComponent(rBtnGigante)
                            .addComponent(rBtnArquero))
                        .addGap(0, 95, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelPersonajeLayout.setVerticalGroup(
            panelPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonajeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panelPersonajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(rBtnCaballero))
                .addGap(18, 18, 18)
                .addComponent(rBtnArquero)
                .addGap(18, 18, 18)
                .addComponent(rBtnMago)
                .addGap(18, 18, 18)
                .addComponent(rBtnGigante)
                .addGap(18, 18, 18)
                .addComponent(rBtnDragon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnComprarPrj)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Personajes", panelPersonaje);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setLabelFor(panelPersonaje);
        jLabel3.setText("Seleccione un Objeto");

        grupoItem.add(rBtnSemilla);
        rBtnSemilla.setText("Semilla de la vida");

        grupoItem.add(rBtnElixir);
        rBtnElixir.setText("Elixir verde");

        grupoItem.add(rBtnCapa);
        rBtnCapa.setText("Capa de movilidad");

        btnComprarItem.setText("Comprar Objeto");
        btnComprarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarItemActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("50 Oro");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("25 Oro");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("75 Oro");

        javax.swing.GroupLayout panelItemLayout = new javax.swing.GroupLayout(panelItem);
        panelItem.setLayout(panelItemLayout);
        panelItemLayout.setHorizontalGroup(
            panelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelItemLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnComprarItem))
                    .addGroup(panelItemLayout.createSequentialGroup()
                        .addGroup(panelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelItemLayout.createSequentialGroup()
                                .addComponent(rBtnCapa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8))
                            .addGroup(panelItemLayout.createSequentialGroup()
                                .addComponent(rBtnElixir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelItemLayout.createSequentialGroup()
                                .addComponent(rBtnSemilla)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 95, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelItemLayout.setVerticalGroup(
            panelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(panelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBtnSemilla)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(panelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBtnElixir)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(panelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBtnCapa)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(btnComprarItem)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Item", panelItem);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setLabelFor(panelPersonaje);
        jLabel4.setText("Seleccione una mejora");

        grupoMejora.add(rBtnMasVida);
        rBtnMasVida.setText("Vida");

        grupoMejora.add(rBtnMasDanio);
        rBtnMasDanio.setText("Daño");

        grupoMejora.add(rBtnMasMov);
        rBtnMasMov.setText("Movilidad");

        btnComprarMejora.setText("Comprar Mejora");
        btnComprarMejora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarMejoraActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("80 Oro");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("125 Oro");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("500 Oro");

        javax.swing.GroupLayout panelMejoraLayout = new javax.swing.GroupLayout(panelMejora);
        panelMejora.setLayout(panelMejoraLayout);
        panelMejoraLayout.setHorizontalGroup(
            panelMejoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMejoraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMejoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMejoraLayout.createSequentialGroup()
                        .addComponent(rBtnMasVida)
                        .addGroup(panelMejoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMejoraLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnComprarMejora))
                            .addGroup(panelMejoraLayout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addGroup(panelMejoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))
                                .addGap(0, 93, Short.MAX_VALUE))))
                    .addGroup(panelMejoraLayout.createSequentialGroup()
                        .addGroup(panelMejoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rBtnMasDanio)
                            .addComponent(rBtnMasMov))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelMejoraLayout.setVerticalGroup(
            panelMejoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMejoraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(panelMejoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBtnMasVida)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(panelMejoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBtnMasDanio)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(panelMejoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBtnMasMov)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(btnComprarMejora)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Mejoras", panelMejora);

        jLabel2.setFont(new java.awt.Font("Nimbus Sans", 3, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/oro.png"))); // NOI18N
        jLabel2.setLabelFor(jPanel1);

        cantidadOroLbl.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidadOroLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cantidadOroLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarPrjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarPrjActionPerformed
        if (rBtnCaballero.isSelected()) {
            System.out.println("caballero");
            tienda.comprarPersonajeJugable(1);
        } else if (rBtnArquero.isSelected()) {
            System.out.println("arquero");
            tienda.comprarPersonajeJugable(2);
        } else if (rBtnMago.isSelected()) {
            System.out.println("mago");
            tienda.comprarPersonajeJugable(3);
        } else if (rBtnGigante.isSelected()) {
            System.out.println("gigante");
            tienda.comprarPersonajeJugable(4);
        } else if (rBtnDragon.isSelected()) {
            System.out.println("dragon");
            tienda.comprarPersonajeJugable(5);
        } else {
            alertMessage("Debe seleccionar un personaje a comprar");
        }
        refrecshLabelOro();
    }//GEN-LAST:event_btnComprarPrjActionPerformed

    private void btnComprarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarItemActionPerformed
        if (rBtnSemilla.isSelected()) {
            System.out.println("Semilla de la vida");
            tienda.comprarObjetos(1);
        } else if (rBtnElixir.isSelected()) {
            System.out.println("Elixir verde");
            tienda.comprarObjetos(2);
        } else if (rBtnCapa.isSelected()) {
            System.out.println("Capa de...");
            tienda.comprarObjetos(3);
        } else {
            alertMessage("Debe seleccionar un objeto a comprar");
        }
        refrecshLabelOro();
    }//GEN-LAST:event_btnComprarItemActionPerformed

    private void btnComprarMejoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarMejoraActionPerformed
        if (rBtnMasVida.isSelected()) {
            System.out.println("Mejorar vida");
            tienda.comprarMejoras(1);
        } else if (rBtnMasDanio.isSelected()) {
            System.out.println("Mejorar Danio");
            tienda.comprarMejoras(2);
        } else if (rBtnMasMov.isSelected()) {
            System.out.println("Mejorar movimiento");
            tienda.comprarMejoras(3);
        } else {
            alertMessage("Debe seleccionar una mejora a comprar");
        }
        refrecshLabelOro();
    }//GEN-LAST:event_btnComprarMejoraActionPerformed

    private void alertMessage(String msj) {
        JOptionPane.showMessageDialog(null,
                msj,
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }

    public void setJg(JugadorUs jg) {
        this.jg = jg;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprarItem;
    private javax.swing.JButton btnComprarMejora;
    private javax.swing.JButton btnComprarPrj;
    private javax.swing.JLabel cantidadOroLbl;
    private javax.swing.ButtonGroup grupoItem;
    private javax.swing.ButtonGroup grupoMejora;
    private javax.swing.ButtonGroup grupoPersj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelItem;
    private javax.swing.JPanel panelMejora;
    private javax.swing.JPanel panelPersonaje;
    private javax.swing.JRadioButton rBtnArquero;
    private javax.swing.JRadioButton rBtnCaballero;
    private javax.swing.JRadioButton rBtnCapa;
    private javax.swing.JRadioButton rBtnDragon;
    private javax.swing.JRadioButton rBtnElixir;
    private javax.swing.JRadioButton rBtnGigante;
    private javax.swing.JRadioButton rBtnMago;
    private javax.swing.JRadioButton rBtnMasDanio;
    private javax.swing.JRadioButton rBtnMasMov;
    private javax.swing.JRadioButton rBtnMasVida;
    private javax.swing.JRadioButton rBtnSemilla;
    // End of variables declaration//GEN-END:variables
}
